# Generated by Django 3.1.2 on 2020-11-19 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MusicRecommenderApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_data',
        ),
    ]
