# Generated by Django 3.1.3 on 2020-12-25 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MusicRecommenderApp', '0002_delete_user_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedTracks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('album', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('artist_id', models.CharField(max_length=60)),
                ('release_date', models.DateField()),
                ('song_length', models.DecimalField(decimal_places=10, max_digits=50)),
                ('popularity', models.DecimalField(decimal_places=10, max_digits=50)),
                ('acousticness', models.DecimalField(decimal_places=10, max_digits=50)),
                ('danceability', models.DecimalField(decimal_places=10, max_digits=50)),
                ('energy', models.DecimalField(decimal_places=10, max_digits=50)),
                ('instrumentalness', models.DecimalField(decimal_places=10, max_digits=50)),
                ('key', models.DecimalField(decimal_places=10, max_digits=50)),
                ('liveness', models.DecimalField(decimal_places=10, max_digits=50)),
                ('speechiness', models.DecimalField(decimal_places=10, max_digits=50)),
                ('tempo', models.DecimalField(decimal_places=10, max_digits=50)),
                ('time_signature', models.DecimalField(decimal_places=10, max_digits=50)),
                ('valence', models.DecimalField(decimal_places=10, max_digits=50)),
                ('mode', models.DecimalField(decimal_places=10, max_digits=50)),
                ('user_id', models.CharField(max_length=60)),
            ],
        ),
    ]
