# Generated by Django 3.1.3 on 2020-12-26 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicRecommenderApp', '0003_savedtracks'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
