# Generated by Django 3.1.3 on 2020-12-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicRecommenderApp', '0004_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedtracks',
            name='loudness',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='savedtracks',
            name='release_date',
            field=models.CharField(max_length=200),
        ),
    ]
