# Generated by Django 3.1.3 on 2020-12-26 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MusicRecommenderApp', '0005_auto_20201226_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersTracks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('album', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('artist_id', models.CharField(max_length=60)),
                ('release_date', models.CharField(max_length=200)),
                ('song_length', models.DecimalField(decimal_places=10, max_digits=50)),
                ('popularity', models.DecimalField(decimal_places=10, max_digits=50)),
                ('acousticness', models.DecimalField(decimal_places=10, max_digits=50)),
                ('danceability', models.DecimalField(decimal_places=10, max_digits=50)),
                ('energy', models.DecimalField(decimal_places=10, max_digits=50)),
                ('instrumentalness', models.DecimalField(decimal_places=10, max_digits=50)),
                ('key', models.DecimalField(decimal_places=10, max_digits=50)),
                ('liveness', models.DecimalField(decimal_places=10, max_digits=50)),
                ('loudness', models.DecimalField(decimal_places=10, max_digits=50)),
                ('speechiness', models.DecimalField(decimal_places=10, max_digits=50)),
                ('tempo', models.DecimalField(decimal_places=10, max_digits=50)),
                ('time_signature', models.DecimalField(decimal_places=10, max_digits=50)),
                ('valence', models.DecimalField(decimal_places=10, max_digits=50)),
                ('mode', models.DecimalField(decimal_places=10, max_digits=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='SavedTracks',
        ),
    ]
