# Generated by Django 3.1.3 on 2020-12-27 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MusicRecommenderApp', '0007_auto_20201227_0024'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userstracks',
            unique_together=set(),
        ),
    ]
