# Generated by Django 3.1.3 on 2020-12-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicRecommenderApp', '0008_auto_20201227_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstracks',
            name='user_id',
            field=models.CharField(max_length=60),
        ),
    ]
