# Generated by Django 3.1.3 on 2020-12-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicRecommenderApp', '0009_auto_20201227_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstracks',
            name='user_id',
            field=models.TextField(max_length=60),
        ),
    ]
